Repository SafeKingMall/frontend, pull requests merged in 2022-11, with the labels that each got.

#5 Feat/sign in page
  src/App.css
  src/App.tsx
  src/global.d.ts
  src/pages/SignIn/SignIn.module.css
  src/pages/SignIn/index.tsx
  src/pages/SignIn/style.module.css
Labels: Type, format, Rename, Design

#10 Design/MyPagePw
  package.json
  public/index.html
  src/App.tsx
  src/components/index.ts
  src/pages/MyPagePw/index.tsx
  src/pages/MyPagePw/style.ts
  yarn.lock
Labels: Setting, format, Rename, Design

#16 AdminSignIn Page/#15
  src/App.tsx
  src/pages/AdminSignIn/index.tsx
  src/pages/AdminSignIn/style.ts
  src/pages/AdminSignUp/index.tsx
  src/pages/AdminSignUp/style.module.css
  src/pages/EditSignIn/index.tsx
  src/pages/EditSignUp/index.tsx
  src/pages/EditSignUp/style.module.css
  src/pages/index.ts
Labels: Rename, Design

#21 MyPage(main)/#19
  src/pages/MyPage/index.tsx
  src/pages/MyPage/style.module.css
  src/pages/MyPage/style.ts
Labels: Design

#35 design/MainPage/#32
  public/index.html
  src/pages/MainPage/index.tsx
  src/pages/MainPage/style.ts
Labels: Setting, Design

#39 design/MyPageWd/#38
  src/pages/MyPage/MyPageWd/index.tsx
  src/pages/MyPage/MyPageWd/style.ts
  src/routes/Router.tsx
  src/styles/globalStyles.ts
Labels: Setting, Rename, Design

#41 design/EditMenudesign/#34
  src/components/Edit/EditMenu/index.tsx
  src/components/Edit/EditMenu/style.ts
Labels: format, Design

#44 design/SignUp1/#43
  src/pages/SignUp/SignUp1/index.tsx
  src/pages/SignUp/SignUp1/style.ts
  src/pages/SignUp/SignUp2/index.tsx
  src/pages/SignUp/SignUp3/index.tsx
  src/pages/SignUp/SignUp4/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.module.css
  src/pages/index.ts
  src/routes/Router.tsx
Labels: Rename, Design

#49 design/MyPageMenu_Final/#48
  src/components/user/MyPageMenu/MyPageMenu.module.css
  src/components/user/MyPageMenu/index.tsx
  src/components/user/MyPageMenu/style.ts
  src/pages/MyPage/MyPageOd/index.tsx
  src/pages/index.ts
  src/routes/Router.tsx
  src/styles/globalStyles.ts
Labels: Setting, remove, Design
